### ISSUE TITLE
the memery judgment might too harsh，cause worker can't get jobs

### ISSUE THREAD

**Issue by mostcute** [filecoin-project/sector-storage#26]
https://github.com/filecoin-project/sector-storage/blob/e4a9a16161e91228eea8c6f0e9772f0c668d8da9/sched.go#L375-L380

a machine only have 128G Physical will show a number less than 128G(maybe 126G)。
so the ERR `sector-storage/sched.go:380     sched: not scheduling on worker 0; not enough physical memory - need: 128922M, have 128911M`  will show ,and cause worker can't get jobs. 

Maybe we should Relaxing conditions ?

**Comment by shepf** [comment]
when i run “lotus” daemon and “lotus-storage-miner run" on the same host（128G physical memory）.  it tell me，not enough physical memory.  It makes me lose.

I agree with mostcute.  @mostcute 
I hope the community will consider it.  At least ensure that daemon and miner can run on the same host(128G) at the same time.

**Comment by magik6k** [comment]
It's now much lower, ~65G / precommit1
